services:
  postgres:
    platform: linux/x86_64
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./scripts/db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  jupyter:
    build: 
      context: .
      args:
        DIR_WORK: "/work"
        REQ_TXT: "requirements.txt"
    image: biobr131/py-metabolomics:latest
    container_name: jupyter
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - ./scripts:/work/scripts
    tty: true
    stdin_open: true

volumes:
  postgres_data:
